# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgbot < Formula
  desc "In-database observability for PostgreSQL"
  homepage "https://pgbot.dev"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.6.1/pgbot_0.6.1_darwin_amd64.tar.gz"
      sha256 "79e7b2e26cc325a58715ed30da932a08f9089b88e259fb47407a51629611f8e4"

      define_method(:install) do
        bin.install "pgbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.6.1/pgbot_0.6.1_darwin_arm64.tar.gz"
      sha256 "f3234d66298ee1d1487776bec2351d5a400931f22508f129835a9b22686d95ae"

      define_method(:install) do
        bin.install "pgbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.6.1/pgbot_0.6.1_linux_amd64.tar.gz"
      sha256 "7bcadda219f1a2341af282b84b87e0de39c393f20b3868ba9c504465a8204549"
      define_method(:install) do
        bin.install "pgbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.6.1/pgbot_0.6.1_linux_arm64.tar.gz"
      sha256 "1d3f55a7bcf3c74273d293579ab8a412bce951da00d0bf25b2536082a607d912"
      define_method(:install) do
        bin.install "pgbot"
      end
    end
  end

  test do
    system bin/"pgbot", "--version"
  end
end
