# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgbot < Formula
  desc "In-database observability for PostgreSQL"
  homepage "https://pgbot.dev"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.4.1/pgbot_0.4.1_darwin_amd64.tar.gz"
      sha256 "810429d4e37600d3948aa2431edfddcef3dcd21a97c2dd05b3f4eba3fd25dd3c"

      define_method(:install) do
        bin.install "pgbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.4.1/pgbot_0.4.1_darwin_arm64.tar.gz"
      sha256 "8e3cdea68c563a18fb16af274c0f4594ecda2f15e7a9fb0da92a1ebb301a4dd5"

      define_method(:install) do
        bin.install "pgbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.4.1/pgbot_0.4.1_linux_amd64.tar.gz"
      sha256 "f77e1dc219c5f21c146464c95fd9f0ed9da22e318a9ec8be4181abd9e322aed5"
      define_method(:install) do
        bin.install "pgbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.4.1/pgbot_0.4.1_linux_arm64.tar.gz"
      sha256 "a04f0311adec1c8d07111c9ded1cf39c4b25528326befa64b46113a53d47f7ee"
      define_method(:install) do
        bin.install "pgbot"
      end
    end
  end

  test do
    system bin/"pgbot", "--version"
  end
end
