# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgbot < Formula
  desc "In-database observability for PostgreSQL"
  homepage "https://pgbot.dev"
  version "0.7.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.7.2/pgbot_0.7.2_darwin_amd64.tar.gz"
      sha256 "9f190ccdd4d7d2c219a988c13acc6f0f620620e431d4689e68703930780bd5ce"

      define_method(:install) do
        bin.install "pgbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.7.2/pgbot_0.7.2_darwin_arm64.tar.gz"
      sha256 "db890f066dcd256fb0e760b1728da2f817c89f12d9b01a6d4b3c3d952b558995"

      define_method(:install) do
        bin.install "pgbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.7.2/pgbot_0.7.2_linux_amd64.tar.gz"
      sha256 "cf0d48c580d3cc2bfbec9526dfacc550623db0126dd10f1c54bd688c5c15d84d"
      define_method(:install) do
        bin.install "pgbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgrundev/pgbot/releases/download/v0.7.2/pgbot_0.7.2_linux_arm64.tar.gz"
      sha256 "36aac98b0b4947f7a8b296c0aad8ff20382c7f313f7abe9dc0ca89edeaa9b292"
      define_method(:install) do
        bin.install "pgbot"
      end
    end
  end

  test do
    system bin/"pgbot", "--version"
  end
end
