# typed: false
# frozen_string_literal: true

# Generated by pgterm's release workflow (packaging/homebrew/formula.sh).
# DO NOT EDIT — the next release overwrites this file.
class Pgterm < Formula
  desc "Terminal UI that watches all your Postgres databases at once"
  homepage "https://pgterm.dev"
  version "0.2.0"
  license "Apache-2.0"

  # No depends_on "pgrundev/tap/pgbot": Homebrew 6 trusts only the formula
  # named on the command line, so a dependency from the same third-party tap
  # is refused ("untrusted tap") for everyone who has not run brew trust.
  # pgbot is installed alongside instead (README) and named in caveats.

  on_macos do
    on_intel do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.2.0/pgterm_0.2.0_darwin_amd64.tar.gz"
      sha256 "e971165148d87e26bb3cff597d4c54709da12c908c07db382af1dc873a27a2bd"
    end
    on_arm do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.2.0/pgterm_0.2.0_darwin_arm64.tar.gz"
      sha256 "9be1d26f3ac06426326ede9cd4456eb6f2f57b6cac10942d0e89a5839d28d104"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.2.0/pgterm_0.2.0_linux_amd64.tar.gz"
      sha256 "ca57bef727d41a84577473b5d63f12d7b072545c7582938c5861a240be63dfd7"
    end
    on_arm do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.2.0/pgterm_0.2.0_linux_arm64.tar.gz"
      sha256 "3787b354071fcc3133ad51027ca2b3b6d15c53872485eea7b35b44f6d6ef9f62"
    end
  end

  def install
    bin.install "pgterm"
  end

  def caveats
    <<~EOS
      pgterm drives pgbot for every diagnostic. If pgbot is not on your PATH yet:
        brew install pgrundev/tap/pgbot
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pgterm --version")
  end
end
