# typed: false
# frozen_string_literal: true

# Generated by pgterm's release workflow (packaging/homebrew/formula.sh).
# DO NOT EDIT — the next release overwrites this file.
class Pgterm < Formula
  desc "Terminal UI that watches all your Postgres databases at once"
  homepage "https://pgterm.dev"
  version "0.3.1"
  license "Apache-2.0"

  # No depends_on "pgrundev/tap/pgbot": Homebrew 6 trusts only the formula
  # named on the command line, so a dependency from the same third-party tap
  # is refused ("untrusted tap") for everyone who has not run brew trust.
  # pgbot is installed alongside instead (README) and named in caveats.

  on_macos do
    on_intel do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.3.1/pgterm_0.3.1_darwin_amd64.tar.gz"
      sha256 "c8a5fae3055b7fc40aab844dfaaebd338929bf0786ca5fb27661239cc0ea95a9"
    end
    on_arm do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.3.1/pgterm_0.3.1_darwin_arm64.tar.gz"
      sha256 "ad7f6b175722d0f06e1e09fd9bad4f510de36778e7eb394046a120194b22a206"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.3.1/pgterm_0.3.1_linux_amd64.tar.gz"
      sha256 "d82373b02144d565da95a301739726529c8bdb8830ccc4cfc7e28607e21d68c8"
    end
    on_arm do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.3.1/pgterm_0.3.1_linux_arm64.tar.gz"
      sha256 "5b282478f6a73c4f1a5571c64f25c73cdce86272f2e976fa620c87bacc024031"
    end
  end

  def install
    bin.install "pgterm"
  end

  def caveats
    <<~EOS
      pgterm drives pgbot for every diagnostic. If pgbot is not on your PATH yet:
        brew install pgrundev/tap/pgbot
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pgterm --version")
  end
end
