# typed: false
# frozen_string_literal: true

# Generated by pgterm's release workflow (packaging/homebrew/formula.sh).
# DO NOT EDIT — the next release overwrites this file.
class Pgterm < Formula
  desc "Terminal UI that watches all your Postgres databases at once"
  homepage "https://pgterm.dev"
  version "0.4.0"
  license "Apache-2.0"

  # No depends_on "pgrundev/tap/pgbot": Homebrew 6 trusts only the formula
  # named on the command line, so a dependency from the same third-party tap
  # is refused ("untrusted tap") for everyone who has not run brew trust.
  # pgbot is installed alongside instead (README) and named in caveats.

  on_macos do
    on_intel do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.4.0/pgterm_0.4.0_darwin_amd64.tar.gz"
      sha256 "84172c2dfe4f3ebfcca333673ed40f7f67150467adae214125f61e3d85851230"
    end
    on_arm do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.4.0/pgterm_0.4.0_darwin_arm64.tar.gz"
      sha256 "1f443107233fbbc9b8d0d696f35398bbb57f568549d414f131959bed70f0f579"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.4.0/pgterm_0.4.0_linux_amd64.tar.gz"
      sha256 "d96a72173b3c382e378438bfb7c0b87c2d3ea63d8ffc9fc0eb89f4a3ec5b62ed"
    end
    on_arm do
      url "https://github.com/pgrundev/pgterm/releases/download/v0.4.0/pgterm_0.4.0_linux_arm64.tar.gz"
      sha256 "678714a68b1b7bd80bfcb6c0fc3b517bb1d1170f128c219adf9e0ceb9cca9642"
    end
  end

  def install
    bin.install "pgterm"
  end

  def caveats
    <<~EOS
      pgterm drives pgbot for every diagnostic. If pgbot is not on your PATH yet:
        brew install pgrundev/tap/pgbot
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pgterm --version")
  end
end
